upstream costflow {
    server app:8000;
    keepalive 32;
}

server {

    listen 80;
    server_name app.arpcotiza.bid;

    location /static/ {
        alias /app/app/static/;

        expires 30d;
        access_log off;

        add_header Cache-Control "public";
    }

    location / {

        proxy_pass http://costflow;

        proxy_http_version 1.1;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

        proxy_set_header Connection "";

        proxy_read_timeout 300;

        proxy_connect_timeout 60;

        proxy_send_timeout 300;
    }
}