"""sesiones persistentes

Revision ID: 0cf8430862c1
Revises: a306fc773a3b
Create Date: 2026-06-16 13:35:17.732232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf8430862c1'
down_revision = 'a306fc773a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesion_proveedor',
    sa.Column('proveedor', sa.String(length=50), nullable=False),
    sa.Column('cookies', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('proveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesion_proveedor')
    # ### end Alembic commands ###
