"""proveedor credenciales

Revision ID: 1efc8dd28df4
Revises: d965d053105e
Create Date: 2026-07-21 12:42:02.832199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efc8dd28df4'
down_revision = 'd965d053105e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor_credenciales',
    sa.Column('id_credenciales', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('credenciales', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id_proveedor'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_credenciales'),
    sa.UniqueConstraint('id_proveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor_credenciales')
    # ### end Alembic commands ###
