"""agrupaciones

Revision ID: 211f7dad30d9
Revises: e29fd983651e
Create Date: 2026-07-10 12:26:47.426369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211f7dad30d9'
down_revision = 'e29fd983651e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agrupacion',
    sa.Column('id_agrupacion', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], ),
    sa.PrimaryKeyConstraint('id_agrupacion')
    )
    op.create_table('agrupacion_detalle',
    sa.Column('id_agrupacion_detalle', sa.Integer(), nullable=False),
    sa.Column('id_agrupacion', sa.Integer(), nullable=False),
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_agrupacion'], ['agrupacion.id_agrupacion'], ),
    sa.ForeignKeyConstraint(['id_detalle'], ['orden_detalle.id_detalle'], ),
    sa.PrimaryKeyConstraint('id_agrupacion_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agrupacion_detalle')
    op.drop_table('agrupacion')
    # ### end Alembic commands ###
