"""campos nuevos usuario

Revision ID: 588608c24e13
Revises: a7efaa3d1f76
Create Date: 2026-07-02 12:54:44.037955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588608c24e13'
down_revision = 'a7efaa3d1f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('puesto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('url_firma', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('url_firma')
        batch_op.drop_column('puesto')
        batch_op.drop_column('numero')

    # ### end Alembic commands ###
