"""nuevos campos orden

Revision ID: 5e8f0a6f682f
Revises: d05b21870664
Create Date: 2026-07-02 11:13:48.556035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8f0a6f682f'
down_revision = 'd05b21870664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vigencia', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tipo_cotizacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('informacion_adicional', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('terminos_condiciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('incluir_firma', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_column('incluir_firma')
        batch_op.drop_column('terminos_condiciones')
        batch_op.drop_column('informacion_adicional')
        batch_op.drop_column('tipo_cotizacion')
        batch_op.drop_column('vigencia')

    # ### end Alembic commands ###
