"""seguimiento

Revision ID: 7e3c1c5400b1
Revises: de49ec750c0b
Create Date: 2026-07-16 13:24:00.229394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3c1c5400b1'
down_revision = 'de49ec750c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguimiento',
    sa.Column('id_seguimiento', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('frecuencia_horas', sa.Integer(), nullable=False),
    sa.Column('ultimo_escaneo', sa.DateTime(), nullable=True),
    sa.Column('proximo_escaneo', sa.DateTime(), nullable=True),
    sa.Column('ultimo_correo', sa.DateTime(), nullable=True),
    sa.Column('cambio_precio', sa.Boolean(), nullable=True),
    sa.Column('sin_stock', sa.Boolean(), nullable=True),
    sa.Column('mejor_oferta', sa.Boolean(), nullable=True),
    sa.Column('diferencia_minima', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], ),
    sa.PrimaryKeyConstraint('id_seguimiento'),
    sa.UniqueConstraint('id_orden')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguimiento')
    # ### end Alembic commands ###
