"""cambio tipo de variable informacion_adicional a JSON

Revision ID: a7efaa3d1f76
Revises: 5e8f0a6f682f
Create Date: 2026-07-02 11:30:31.088382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7efaa3d1f76'
down_revision = '5e8f0a6f682f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('informacion_adicional',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('informacion_adicional',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
