"""campos informacion_adicional y notas_internas

Revision ID: bccbedf14815
Revises: f0e0ac3cdb65
Create Date: 2026-07-07 17:50:42.495845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bccbedf14815'
down_revision = 'f0e0ac3cdb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('informacion_adicional', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notas_internas', sa.Text(), nullable=True))
        batch_op.alter_column('producto',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_detalle', schema=None) as batch_op:
        batch_op.alter_column('producto',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('notas_internas')
        batch_op.drop_column('informacion_adicional')

    # ### end Alembic commands ###
