"""ordenes de compra

Revision ID: cc50564c3723
Revises: 4e8910a6f62a
Create Date: 2026-04-14 17:09:17.281558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc50564c3723'
down_revision = '4e8910a6f62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('orden',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('clave_orden', sa.String(length=45), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('comprador', sa.String(length=150), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_orden'),
    sa.UniqueConstraint('clave_orden')
    )
    op.create_table('orden_detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('producto', sa.String(length=255), nullable=False),
    sa.Column('clave_producto', sa.String(length=100), nullable=True),
    sa.Column('url_producto', sa.String(length=500), nullable=True),
    sa.Column('url_imagen', sa.String(length=500), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ganancia_unitaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_detalle')
    op.drop_table('orden')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
