"""productos locales

Revision ID: d05b21870664
Revises: 0cf8430862c1
Create Date: 2026-06-19 13:43:58.187529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05b21870664'
down_revision = '0cf8430862c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('clave_producto', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('existencia', sa.Integer(), nullable=True),
    sa.Column('clave_interna', sa.String(length=100), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('existencia_producto',
    sa.Column('id_existencia', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('sucursal', sa.String(length=50), nullable=False),
    sa.Column('existencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_existencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('existencia_producto')
    op.drop_table('producto')
    # ### end Alembic commands ###
