"""campo cookies sesion proveedor a text

Revision ID: d965d053105e
Revises: 7e3c1c5400b1
Create Date: 2026-07-20 14:05:47.694759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd965d053105e'
down_revision = '7e3c1c5400b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesion_proveedor', schema=None) as batch_op:
        batch_op.alter_column('cookies',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesion_proveedor', schema=None) as batch_op:
        batch_op.alter_column('cookies',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###
