"""agrupaciones informacion adicional

Revision ID: de49ec750c0b
Revises: 211f7dad30d9
Create Date: 2026-07-10 13:08:18.417612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de49ec750c0b'
down_revision = '211f7dad30d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agrupacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('informacion_adicional', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agrupacion', schema=None) as batch_op:
        batch_op.drop_column('informacion_adicional')

    # ### end Alembic commands ###
