"""campo clave opcional

Revision ID: de521cebc1b3
Revises: bccbedf14815
Create Date: 2026-07-08 12:36:34.247984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de521cebc1b3'
down_revision = 'bccbedf14815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('clave_orden',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('clave_orden',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    # ### end Alembic commands ###
