"""departamentos unam

Revision ID: e29fd983651e
Revises: de521cebc1b3
Create Date: 2026-07-08 14:00:55.628835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29fd983651e'
down_revision = 'de521cebc1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento_unam',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('prefijo', sa.String(length=8), nullable=False),
    sa.Column('puntos_entrega', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id_departamento'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departamento_unam')
    # ### end Alembic commands ###
