"""campo incluir_imagenes orden

Revision ID: f0e0ac3cdb65
Revises: 588608c24e13
Create Date: 2026-07-07 10:46:48.592061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e0ac3cdb65'
down_revision = '588608c24e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incluir_imagenes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_column('incluir_imagenes')

    # ### end Alembic commands ###
