"""porcentaje ganancia

Revision ID: ff62c6e9e7ed
Revises: cc50564c3723
Create Date: 2026-06-02 10:58:22.990781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff62c6e9e7ed'
down_revision = 'cc50564c3723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('margen_ganancia', sa.Numeric(precision=5, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_detalle', schema=None) as batch_op:
        batch_op.drop_column('margen_ganancia')

    # ### end Alembic commands ###
